sudo: required
services:
  - docker
language: generic 

before_install:
  - docker build -t xpamou1/reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true xpamou1/reactapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "reactapp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-743788846417"
  bucket_path: "reactapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY