sudo: required
services:
  - docker
language: generic 

before_install:
  - docker build -t xpamou1/reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true xpamou1/reactapp npm run test -- --coverage