version: '3'
services: 
  web:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    ports: 
      - 80:3000
    volumes: 
      - /app/node_modules # Do not try to map this folder inside in container
      - .:/app
  tests:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] 